import os
import json
import re
from collections import defaultdict

# 설정
LANG_DIR = './lang'
TXT_DIR = './txt'            # TXT 파일이 저장될 폴더
OUTPUT_JS = 'rendered.json.js'

def nested_dict():
    """자동으로 깊은 딕셔너리를 생성해주는 헬퍼 함수"""
    return defaultdict(nested_dict)

def main():
    if not os.path.exists(LANG_DIR):
        print(f"오류: '{LANG_DIR}' 폴더가 없습니다. 폴더를 생성해주세요.")
        return

    # txt 폴더가 없으면 자동 생성
    os.makedirs(TXT_DIR, exist_ok=True)

    # 1. 사용 가능한 언어 폴더 스캔 (예: en, ko, ja, zh)
    available_langs = [d for d in os.listdir(LANG_DIR) if os.path.isdir(os.path.join(LANG_DIR, d))]
    available_langs.sort()
    
    print(f"인식된 언어: {available_langs}")

    # 데이터 저장용 딕셔너리
    master_data = nested_dict()
    txt_data = defaultdict(lambda: defaultdict(list))

    # 2. 파일 순회 및 파싱
    for lang in available_langs:
        lang_path = os.path.join(LANG_DIR, lang)
        
        for filename in os.listdir(lang_path):
            if not filename.endswith('.json'):
                continue
                
            match = re.search(r'\d+', filename)
            if not match:
                continue
            chapter = str(int(match.group()))
            
            filepath = os.path.join(lang_path, filename)
            try:
                with open(filepath, 'r', encoding='utf-8') as f:
                    lang_json = json.load(f)
                    
                for key, text in lang_json.items():
                    # =============== 수정된 그룹화 로직 ===============
                    # 1순위: _slash_ 가 있으면 그걸 기준으로 분리 (오브젝트명과 이벤트명 분리)
                    if '_slash_' in key:
                        group_name, msg_id = key.split('_slash_', 1)
                    # 2순위: _slash_가 없고 _gml_만 있으면 그걸로 분리
                    elif '_gml_' in key:
                        group_name, msg_id = key.split('_gml_', 1)
                    # 3순위: 둘 다 없으면 (예: special_name_check_14) 마지막 숫자로 분리
                    else:
                        match = re.search(r'^(.*)_(\d+)$', key)
                        if match:
                            group_name = match.group(1)
                            msg_id = match.group(2)
                        else:
                            group_name = 'general'
                            msg_id = key
                    # =================================================
                        
                    # 데이터 병합
                    master_data[chapter][group_name][msg_id][lang] = text
                    # TXT 데이터 추가
                    txt_data[lang][chapter].append(f"[{key}] {text}")
                    
            except Exception as e:
                print(f"파일 읽기 오류 ({filepath}): {e}")

    # 3. rendered.json.js 파일 생성
    print("데이터 병합 중... rendered.json.js 생성")
    final_dict = json.loads(json.dumps(master_data))
    
    js_content = f"""// Auto-generated by build.py
window.availableLangs = {json.dumps(available_langs, ensure_ascii=False)};
window.rendered = {json.dumps(final_dict, ensure_ascii=False, separators=(',', ':'))};
"""
    with open(OUTPUT_JS, 'w', encoding='utf-8') as f:
        f.write(js_content)
        
    # 4. 언어별 TXT 파일을 'txt' 폴더 안에 생성
    for lang in available_langs:
        txt_filename = f"DELTARUNE_{lang}.txt"
        txt_filepath = os.path.join(TXT_DIR, txt_filename)
        
        print(f"텍스트 덤프 생성 중... {txt_filepath}")
        
        with open(txt_filepath, 'w', encoding='utf-8') as f:
            f.write(f"=== DELTARUNE TEXT DUMP ({lang.upper()}) ===\n\n")
            
            for chapter in sorted(txt_data[lang].keys(), key=lambda x: int(x)):
                f.write(f"\n{'='*20}\n")
                f.write(f"    CHAPTER {chapter}\n")
                f.write(f"{'='*20}\n\n")
                
                for line in txt_data[lang][chapter]:
                    f.write(line + "\n")

    print("\n✅ 성공적으로 모든 빌드가 완료되었습니다!")

if __name__ == '__main__':
    main()